# Generated by Django 4.0.4 on 2022-04-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_alter_smodel_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smodel',
            name='PIN',
        ),
        migrations.RemoveField(
            model_name='smodel',
            name='emailAdd',
        ),
        migrations.RemoveField(
            model_name='smodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='smodel',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='smodel',
            name='student_ID',
        ),
    ]
