# Generated by Django 4.0.4 on 2022-04-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0003_remove_smodel_pin_remove_smodel_emailadd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smodel',
            name='user',
        ),
    ]
